version: "3.7"
services:
  app-vue:
    container_name: app-vue
    build:
      context: ./vue

  orchestrator:
    container_name: orchestrator
    ports:
      - 80:80
    build:
      context: .

# networks:
#   typescript:
#     external:
#       name: typescript_typescript
