version: "3.7"
services:
  app-vue:
    container_name: app-vue
    build:
      context: ./vue

  orchestrator:
    container_name: orchestrator
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
    ports:
      - 80:80
      - 443:443
    build:
      context: .

# networks:
#   typescript:
#     external:
#       name: typescript_typescript
