version: "3.7"
services:
  orchestrator:
    container_name: orchestrator
    volumes:
      - code:/var/www/
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
    ports:
      - 80:80
      - 443:443
    networks:
      - gerador-cnpj
    build:
      context: .

networks:
  gerador-cnpj:
    external:
      name: gerador-cnpj_network

volumes:
  code:
    driver: local