version: "3.7"
services:
  app-vue:
    container_name: app-vue
    build:
      context: ./vue
    networks:
      - typescript

  orchestrator:
    container_name: orchestrator
    ports:
      - 80:80

    networks:
      - typescript
    build:
      context: .

networks:
  typescript:
    external:
      name: typescript_typescript
